# GitHub Action for deploying MkDocs to GitHub Pages
name: Deploy Docs

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
      - feature # Also trigger on feature branch for testing
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission for creating the gh-pages branch
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use a specific Python version for consistency

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Action for deploying to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided token
          publish_dir: ./site # The directory where MkDocs builds the site
          force_orphan: true # Force push to ensure clean deployment