# GitHub Action for deploying MkDocs to GitHub Pages
name: Deploy Docs

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission for creating the gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3.x

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions
          # If you decide to use the analytics plugin again:
          # pip install mkdocs-google-analytics-plugin
          # If you need any other custom plugins, install them here.

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Action for deploying to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided token
          publish_dir: ./site # The directory where MkDocs builds the site